/*
 * This source file was generated by the Gradle 'init' task
 */
package org.lab1;

import org.lab1.courier.Courier;

public class App {
    public static void main(String[] args) {
        while(true)
        {
            Courier cor = new Courier();

            System.out.println(cor.getId());

            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }
}
