/*
 * This source file was generated by the Gradle 'init' task
 */
package org.lab1;

import org.lab1.courier.Courier;
import org.lab1.courier.CourierRepository;

public class App {
    public static void main(String[] args) {
        CourierRepository cr = new CourierRepository();
        var c = new Courier();
        cr.remove(c);
    }
}
